version: '3.1'

services:
  elastic:
    image: elasticsearch:7.14.2
    container_name: elastic
    environment:
      - discovery.type=single-node
    volumes:
      - ./data:/usr/share/elasticsearch/data
    ports:
      - 9300:9300
      - 9200:9200
    networks:
      - elastic

networks:
  elastic:
    driver: bridge